### ISSUE TITLE
Whats an RT Apollo?

### ISSUE THREAD

**Issue by jeveloper** [PagerDuty/scheduler#17]
Thanks for sharing this amazing scheduler.

Just curious , it appears that rt-apollo is a private project , however its referred as an example.
Any chance you can update a user guide with a portion of that example?

thanks

**Comment by cdegroot** [comment]
Apollo is indeed an internal service; we probably missed that reference when scrubbing the documentation before open sourcing this. I'll keep this issue open and have a look later this week.

**Comment by jeveloper** [comment]
Great

**Comment by cdegroot** [comment]
Hi Serge - we've scrubbed the docs, and we're going to think about some example code. It's a bit involved (this is not a simple library you just pull in and integrate with a line of code ;-)) so we need to think what would be useful. Closing the issue for now - thanks for the feedback!

**Comment by jeveloper** [comment]
I completely understand :)
