### ISSUE TITLE
The ability to cancel a scheduled task

### ISSUE THREAD

**Issue by jfrense** [PagerDuty/scheduler#32]
Is there a way to cancel an already scheduled task that has not run yet?

**Comment by jppierri** [comment]
Hi @jfrense, you can use the Admin HTTP interface to modify or cancel an existing task: https://github.com/PagerDuty/scheduler/blob/master/http-admin/src/main/scala/com/pagerduty/scheduler/admin/http/AdminServlet.scala#L88
