### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by jan-schumacher** [PagerDuty/scheduler#36]
Hi,
I saw the talk about this tool on youtube and was really joyful about the opportunities that this tool could bring. Unfortunately the documentation is so bad and does not help alot when there are questions about how to implement this lib and it's dependencies. Especially the client side is a big questionmark for me. How do I register what to do when a task is running? How do I tell the lib when my task should run?
Could you please provide some documentation about a simple sample task that does prints out a "hello scheduler" when the scheduled task is running? 
That would be great.

**Comment by justinmichaud** [comment]
Hi Jan,

While we would gladly accept a PR with a sample application, at the moment it looks like it will be a while before we can publish one. Sorry about that.

In the meantime, the example code in https://github.com/PagerDuty/scheduler/issues/21 may be helpful.
